import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

import "./globals.css";
import Header from "@/components/Header";
import ApolloWrapper from "@/components/ApolloWrapper";

// Make Apollo include useful error messages by default
loadDevMessages();
loadErrorMessages();

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Header />
          {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
