package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	radiochatter "github.com/Michael-F-Bryan/radio-chatter/pkg"
	"github.com/Michael-F-Bryan/radio-chatter/pkg/graphql/model"
)

// Streams is the resolver for the streams field.
func (r *queryResolver) Streams(ctx context.Context, after *string, count int) (*model.StreamsConnection, error) {
	var streams []radiochatter.Stream

	if err := r.db.Find(&streams).Error; err != nil {
		return nil, err
	}

	panic(fmt.Errorf("not implemented: Streams - streams"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
