name: Continuous Integration

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.21"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  golang:
    name: Go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Fetch Dependencies
        run: go mod download -x
      - name: Build
        run: mkdir -p ./out && go build -v -o ./out ./...
      - name: Test
        run: go test -v -race -cover -coverprofile coverage.out ./...
      - name: Print Test Coverage
        run: go tool cover -func=coverage.out
      - name: Coverage Report
        run: go tool cover -html=coverage.out -o=coverage.html
      - name: Lints
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: golang-artifacts
          path: |
            out/
            coverage.html
          retention-days: 14

  docker-containers:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
